[server]
listen_addr = "0.0.0.0:80"
# We set this timemout to avoid
# HeaderTimeout error which is caused by prometheus
server_header_read_timeout = 6000 # ms
upstream_max_idle_per_host = 10
upstream_timeout = 1000 # ms
set_header_x_forwarded_for = "append"
set_header_x_forwarded_host = "overwrite"
set_header_x_forwarded_port = "overwrite"
set_header_x_forwarded_proto = "overwrite"
set_header_forwarded = "append"
client_ip_header = "X-Real-IP"

[balancer]
policy = "least_connections"

[healthcheck]
enabled = false
path = "/health"
interval = 5000 # ms

[[hosts]]
host = "backend-1"
weight = 1

[[hosts]]
host = "backend-2"
weight = 1

[[hosts]]
host = "backend-3"
weight = 1